name: Build Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: [
      'self-hosted',
      'landing'
    ]
    if: github.event.pull_request.merged == false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 22.x
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: |
          #!/bin/bash
          npm ci
      - name: Build
        run: |
          #!/bin/bash
          npm run  build

