name: deploy-angular.yml
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Angular App
    runs-on: [
      '111']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install
        run: |
          #!/bin/bash
            npm install
      - name: build
        run: |
          #!/bin/bash
          npm run build
      - name: start
        run: |
          #!/bin/bash
          npm run start
      - name:
        run: |
          #!/bin/bash
          bash .github/workflows/run.sh
